### ISSUE TITLE
[❗Assignment] 전체통합(2/7)까지 필요한 사항

### ISSUE THREAD

**Issue by woo-yu** [Ourdus/OurdusBE#16]
### 진행해야하는 목록
 - [x] main화면
    > Product의 Paging 必 
    > 관련 링크 [1](https://www.baeldung.com/jpa-pagination), [2](https://bezkoder.com/spring-boot-pagination-filter-jpa-pageable/) 
 - [x] 1.2.1 - 회원가입
    >Jwt를 활용한 로그인 및 인증 유지 必
 - [x] 1.3 - ID/Password 찾기
    > 핸드폰번호로 ID(email), 핸드폰번호+ID(email)로 passwd 찾기
    >Email 인증 必 ([spring boot starter mail package](https://www.baeldung.com/spring-email) 이용)
     *이외에 아이디어 있으시면 의견 주세요!
     >그리고, ID/PW 둘다 핸드폰 번호 인증으로 찾는데 이메일 인증으로 찾게 된다면, ID는 어떻게?? (이메일 == 입력 ID)
 - [x] 2.3 - 내 정보
    > GET user/{user_id}에서 해당 화면에 필요한 정보 조회해서 반환하는 mapping 必
    >내 정보 네 가지 중에서는*적립금*만 구현 가능, 나머지는 아직 x라 하드코딩 요청  
 - [x] 2.3.1 - 주문 내역
    > 2.3의 연장선. **주문(Order)** Entity 생성 및 조회 구현 必
 - [x] 2.3.4 - 회원정보 수정 및 주소 추가/수정
    > **주소(배송지, Address)** Entity 생성 및 CRUD 구현 必
 - [x] 2.3.5 회원탈퇴
 - [x] 💥 Data Crawling
   > 임시 데이터로 쓸 내용들(User, 배송지, 주문 등등 긁어올수 없는것), 작품 및 작품 연관 table들

### 프론트에게 요청하는 사항
1. 2.3 내 정보에서 적립금을 제외한 세 가지 항목 하드코딩 요청
2. ID/PW 찾기에서 ID는 무엇을 구분자로?
3. Jwt를 활용한 로그인을 구현할 예정, [참고](https://velog.io/@dsunni/Spring-Boot-React-JWT%EB%A1%9C-%EA%B0%84%EB%8B%A8%ED%95%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0) 요청
4. 작품/클래스의 Option부분 간소화 요청

**Comment by Kimbangg** [comment]
프론트에게 요청하는 사항은 Ourdus main issue 쪽에 달아주면 확인이 용이 할 것 같습니다 :D

프론트쪽에서도 필요 및 질문 사항은 메인 issue에 걸어서 도움 요청하는 쪽으로 하겠습니다~~~!!

*ps
ISSUE 선례를 남겨주셔서, 편하게 작성이 가능했습니다 !
